update_fastlane


default_platform(:ios)

platform :ios do
	lane :tests do
		cocoapods()
		run_tests(
			workspace: ENV["WORKSPACE"],
			devices: ["iPhone 8"],
			scheme: ENV["SCHEME"],
			code_coverage: true
		)
	end
	
	lane :coverage do
		slather(
			scheme: ENV["SCHEME"],
			workspace: ENV["WORKSPACE"],
			proj: ENV["PROJ"],
			teamcity: true, 
			output_directory: "./fastlane/test_output/coverage"
		)
	end
end
