# update_fastlane

default_platform(:ios)

platform :ios do
	lane :tests do
		cocoapods()
		run_tests(
			workspace: "Operation.xcworkspace",
			devices: ["iPhone 8"],
			scheme: "Operation",
			code_coverage: true
		)
	end
	
	lane :coverage do
		slather(
			scheme: "Operation",
			workspace: "Operation.xcworkspace",
			proj: "Operation.xcodeproj",
			teamcity: true, 
			html: true,
			output_directory: "./fastlane/test_output/coverage"
		)
	end
end
